### ISSUE TITLE
Loading "merlin-vertex-dev" kernel - spinning in activity log

### ISSUE THREAD

**Issue by tottenjordan** [GoogleCloudPlatform/nvidia-merlin-on-vertex-ai#26]
After following the setup instruction in the README.md, the activity log has displayed "loading kernel from...  `gcr.io/.../merlin-vertex-dev..` for several hours and the kernel is not available to select for a notebook container. 

![image](https://user-images.githubusercontent.com/39886184/179751173-293a5cbc-b597-47a2-9a6c-0374ee089ed2.png)

**Comment by leiterenato** [comment]
Hi @tottenjordan,
Thanks for opening this bug.
I will run some tests and let you know if I could reproduce the same problem.

**Comment by leiterenato** [comment]
@tottenjordan I could reproduce the same behavior in my environment.
This error is due to an incompatibility of the latest merlin-training container with Vertex AI Workbench.

It fails to register the kernel and hangs the process indefinitely.
Please pull the new code and build a new development container to fix this issue.

Please let me know if you find any other issues.
Thank you
